import {library} from '@fortawesome/fontawesome-svg-core';
import {fab} from '@fortawesome/free-brands-svg-icons';
import {faHouse} from '@fortawesome/free-solid-svg-icons/faHouse';
import {faClock} from '@fortawesome/free-solid-svg-icons/faClock';
import {faGear} from '@fortawesome/free-solid-svg-icons/faGear';
import {faArrowRightFromBracket} from '@fortawesome/free-solid-svg-icons/faArrowRightFromBracket';
import {faChevronDown} from '@fortawesome/free-solid-svg-icons/faChevronDown';
import {faChevronLeft} from '@fortawesome/free-solid-svg-icons/faChevronLeft';
import {faExclamation} from '@fortawesome/free-solid-svg-icons/faExclamation';
import {faSearch} from '@fortawesome/free-solid-svg-icons/faSearch';
import {faSliders} from '@fortawesome/free-solid-svg-icons/faSliders';
import {faPlus} from '@fortawesome/free-solid-svg-icons/faPlus';
import {faTimes} from '@fortawesome/free-solid-svg-icons/faTimes';
import {faCalendar} from '@fortawesome/free-solid-svg-icons/faCalendar';
import {faUser} from '@fortawesome/free-solid-svg-icons/faUser';
import {faEye} from '@fortawesome/free-solid-svg-icons/faEye';
import {faEyeSlash} from '@fortawesome/free-solid-svg-icons/faEyeSlash';
import {faCircleCheck} from '@fortawesome/free-solid-svg-icons/faCircleCheck';

library.add(fab, faHouse, faClock, faGear, faArrowRightFromBracket, faChevronDown, faChevronLeft, faExclamation, faSearch, faSliders, faPlus, faTimes, faCalendar, faUser, faEye, faEyeSlash, faCircleCheck);
